### ISSUE TITLE
ANDY BROWN SHIELD test failed

### ISSUE THREAD

**Issue by linmuzhang** [xxxajk/xmem2#1]
hi,i changed your xmem.h file as below:
# define EXT_RAM 2

.....
# ifndef EXT_RAM_STACK
# define EXT_RAM_STACK 0
# endif

....
# define WANT_TEST_CODE 1

and test code is:
# include <xmem.h>

xmem::SelfTestResults results;
void setup(){
  Serial.begin(9600);
  xmem::begin(true);
}
void loop(){
  results=xmem::selfTest();
  if(!results.succeeded)
    Serial.println("fail");
  else
    Serial.println("success");
    delay(2000);
}

and then i got "fail' ,but andy brown's lib ,i got success with same test code
i want to use your lib ,because want to move stack in xmem,mega2560 internal ram was 
not enough,

platform: arduino IDE 1.0.5
os:window xp sp3

please help,thanks

**Comment by xxxajk** [comment]
Did you got it to work?

**Comment by linmuzhang** [comment]
hi,No,i gave up,i'm not a coder,just interesting
